# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_do_crypto.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import psa_key_attributes_pb2 as psa__key__attributes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='can_do_crypto.proto',
  package='can_do_crypto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63\x61n_do_crypto.proto\x12\rcan_do_crypto\x1a\x18psa_key_attributes.proto\"p\n\tOperation\x12,\n\ncheck_type\x18\x01 \x01(\x0e\x32\x18.can_do_crypto.CheckType\x12\x35\n\nattributes\x18\x02 \x01(\x0b\x32!.psa_key_attributes.KeyAttributes\"\x08\n\x06Result*N\n\tCheckType\x12\x12\n\x0e\x43HECKTYPE_NONE\x10\x00\x12\x07\n\x03USE\x10\x01\x12\x0c\n\x08GENERATE\x10\x02\x12\n\n\x06IMPORT\x10\x03\x12\n\n\x06\x44\x45RIVE\x10\x04\x62\x06proto3'
  ,
  dependencies=[psa__key__attributes__pb2.DESCRIPTOR,])

_CHECKTYPE = _descriptor.EnumDescriptor(
  name='CheckType',
  full_name='can_do_crypto.CheckType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHECKTYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GENERATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IMPORT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DERIVE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_CHECKTYPE)

CheckType = enum_type_wrapper.EnumTypeWrapper(_CHECKTYPE)
CHECKTYPE_NONE = 0
USE = 1
GENERATE = 2
IMPORT = 3
DERIVE = 4



_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='can_do_crypto.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='check_type', full_name='can_do_crypto.Operation.check_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='can_do_crypto.Operation.attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=176,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='can_do_crypto.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=186,
)

_OPERATION.fields_by_name['check_type'].enum_type = _CHECKTYPE
_OPERATION.fields_by_name['attributes'].message_type = psa__key__attributes__pb2._KEYATTRIBUTES
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['CheckType'] = _CHECKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'can_do_crypto_pb2'
  # @@protoc_insertion_point(class_scope:can_do_crypto.Operation)
  })
_sym_db.RegisterMessage(Operation)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'can_do_crypto_pb2'
  # @@protoc_insertion_point(class_scope:can_do_crypto.Result)
  })
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
