# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_keys.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import psa_key_attributes_pb2 as psa__key__attributes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='list_keys.proto',
  package='list_keys',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0flist_keys.proto\x12\tlist_keys\x1a\x18psa_key_attributes.proto\"c\n\x07KeyInfo\x12\x13\n\x0bprovider_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x35\n\nattributes\x18\x03 \x01(\x0b\x32!.psa_key_attributes.KeyAttributes\"\x0b\n\tOperation\"*\n\x06Result\x12 \n\x04keys\x18\x01 \x03(\x0b\x32\x12.list_keys.KeyInfob\x06proto3'
  ,
  dependencies=[psa__key__attributes__pb2.DESCRIPTOR,])




_KEYINFO = _descriptor.Descriptor(
  name='KeyInfo',
  full_name='list_keys.KeyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider_id', full_name='list_keys.KeyInfo.provider_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='list_keys.KeyInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='list_keys.KeyInfo.attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=155,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='list_keys.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=168,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='list_keys.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='list_keys.Result.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=212,
)

_KEYINFO.fields_by_name['attributes'].message_type = psa__key__attributes__pb2._KEYATTRIBUTES
_RESULT.fields_by_name['keys'].message_type = _KEYINFO
DESCRIPTOR.message_types_by_name['KeyInfo'] = _KEYINFO
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyInfo = _reflection.GeneratedProtocolMessageType('KeyInfo', (_message.Message,), {
  'DESCRIPTOR' : _KEYINFO,
  '__module__' : 'list_keys_pb2'
  # @@protoc_insertion_point(class_scope:list_keys.KeyInfo)
  })
_sym_db.RegisterMessage(KeyInfo)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'list_keys_pb2'
  # @@protoc_insertion_point(class_scope:list_keys.Operation)
  })
_sym_db.RegisterMessage(Operation)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'list_keys_pb2'
  # @@protoc_insertion_point(class_scope:list_keys.Result)
  })
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
