# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_authenticators.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='list_authenticators.proto',
  package='list_authenticators',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19list_authenticators.proto\x12\x13list_authenticators\"s\n\x11\x41uthenticatorInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x13\n\x0bversion_maj\x18\x02 \x01(\r\x12\x13\n\x0bversion_min\x18\x03 \x01(\r\x12\x13\n\x0bversion_rev\x18\x04 \x01(\r\x12\n\n\x02id\x18\x05 \x01(\r\"\x0b\n\tOperation\"H\n\x06Result\x12>\n\x0e\x61uthenticators\x18\x01 \x03(\x0b\x32&.list_authenticators.AuthenticatorInfob\x06proto3'
)




_AUTHENTICATORINFO = _descriptor.Descriptor(
  name='AuthenticatorInfo',
  full_name='list_authenticators.AuthenticatorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='list_authenticators.AuthenticatorInfo.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_maj', full_name='list_authenticators.AuthenticatorInfo.version_maj', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_min', full_name='list_authenticators.AuthenticatorInfo.version_min', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_rev', full_name='list_authenticators.AuthenticatorInfo.version_rev', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='list_authenticators.AuthenticatorInfo.id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=165,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='list_authenticators.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=178,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='list_authenticators.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authenticators', full_name='list_authenticators.Result.authenticators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=252,
)

_RESULT.fields_by_name['authenticators'].message_type = _AUTHENTICATORINFO
DESCRIPTOR.message_types_by_name['AuthenticatorInfo'] = _AUTHENTICATORINFO
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthenticatorInfo = _reflection.GeneratedProtocolMessageType('AuthenticatorInfo', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATORINFO,
  '__module__' : 'list_authenticators_pb2'
  # @@protoc_insertion_point(class_scope:list_authenticators.AuthenticatorInfo)
  })
_sym_db.RegisterMessage(AuthenticatorInfo)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'list_authenticators_pb2'
  # @@protoc_insertion_point(class_scope:list_authenticators.Operation)
  })
_sym_db.RegisterMessage(Operation)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'list_authenticators_pb2'
  # @@protoc_insertion_point(class_scope:list_authenticators.Result)
  })
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
