# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prepare_key_attestation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prepare_key_attestation.proto',
  package='prepare_key_attestation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dprepare_key_attestation.proto\x12\x17prepare_key_attestation\"\xdf\x01\n\x1bPrepareKeyAttestationParams\x12\x66\n\x13\x61\x63tivate_credential\x18\x01 \x01(\x0b\x32G.prepare_key_attestation.PrepareKeyAttestationParams.ActivateCredentialH\x00\x1aK\n\x12\x41\x63tivateCredential\x12\x19\n\x11\x61ttested_key_name\x18\x01 \x01(\t\x12\x1a\n\x12\x61ttesting_key_name\x18\x02 \x01(\tB\x0b\n\tmechanism\"U\n\tOperation\x12H\n\nparameters\x18\x01 \x01(\x0b\x32\x34.prepare_key_attestation.PrepareKeyAttestationParams\"\xe1\x01\n\x1bPrepareKeyAttestationOutput\x12\x66\n\x13\x61\x63tivate_credential\x18\x01 \x01(\x0b\x32G.prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredentialH\x00\x1aM\n\x12\x41\x63tivateCredential\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x0e\n\x06public\x18\x02 \x01(\x0c\x12\x19\n\x11\x61ttesting_key_pub\x18\x03 \x01(\x0c\x42\x0b\n\tmechanism\"N\n\x06Result\x12\x44\n\x06output\x18\x01 \x01(\x0b\x32\x34.prepare_key_attestation.PrepareKeyAttestationOutputb\x06proto3'
)




_PREPAREKEYATTESTATIONPARAMS_ACTIVATECREDENTIAL = _descriptor.Descriptor(
  name='ActivateCredential',
  full_name='prepare_key_attestation.PrepareKeyAttestationParams.ActivateCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attested_key_name', full_name='prepare_key_attestation.PrepareKeyAttestationParams.ActivateCredential.attested_key_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attesting_key_name', full_name='prepare_key_attestation.PrepareKeyAttestationParams.ActivateCredential.attesting_key_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=269,
)

_PREPAREKEYATTESTATIONPARAMS = _descriptor.Descriptor(
  name='PrepareKeyAttestationParams',
  full_name='prepare_key_attestation.PrepareKeyAttestationParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activate_credential', full_name='prepare_key_attestation.PrepareKeyAttestationParams.activate_credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PREPAREKEYATTESTATIONPARAMS_ACTIVATECREDENTIAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='mechanism', full_name='prepare_key_attestation.PrepareKeyAttestationParams.mechanism',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=282,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='prepare_key_attestation.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='prepare_key_attestation.Operation.parameters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=369,
)


_PREPAREKEYATTESTATIONOUTPUT_ACTIVATECREDENTIAL = _descriptor.Descriptor(
  name='ActivateCredential',
  full_name='prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredential.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public', full_name='prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredential.public', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attesting_key_pub', full_name='prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredential.attesting_key_pub', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=584,
)

_PREPAREKEYATTESTATIONOUTPUT = _descriptor.Descriptor(
  name='PrepareKeyAttestationOutput',
  full_name='prepare_key_attestation.PrepareKeyAttestationOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activate_credential', full_name='prepare_key_attestation.PrepareKeyAttestationOutput.activate_credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PREPAREKEYATTESTATIONOUTPUT_ACTIVATECREDENTIAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='mechanism', full_name='prepare_key_attestation.PrepareKeyAttestationOutput.mechanism',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=372,
  serialized_end=597,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='prepare_key_attestation.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='prepare_key_attestation.Result.output', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=677,
)

_PREPAREKEYATTESTATIONPARAMS_ACTIVATECREDENTIAL.containing_type = _PREPAREKEYATTESTATIONPARAMS
_PREPAREKEYATTESTATIONPARAMS.fields_by_name['activate_credential'].message_type = _PREPAREKEYATTESTATIONPARAMS_ACTIVATECREDENTIAL
_PREPAREKEYATTESTATIONPARAMS.oneofs_by_name['mechanism'].fields.append(
  _PREPAREKEYATTESTATIONPARAMS.fields_by_name['activate_credential'])
_PREPAREKEYATTESTATIONPARAMS.fields_by_name['activate_credential'].containing_oneof = _PREPAREKEYATTESTATIONPARAMS.oneofs_by_name['mechanism']
_OPERATION.fields_by_name['parameters'].message_type = _PREPAREKEYATTESTATIONPARAMS
_PREPAREKEYATTESTATIONOUTPUT_ACTIVATECREDENTIAL.containing_type = _PREPAREKEYATTESTATIONOUTPUT
_PREPAREKEYATTESTATIONOUTPUT.fields_by_name['activate_credential'].message_type = _PREPAREKEYATTESTATIONOUTPUT_ACTIVATECREDENTIAL
_PREPAREKEYATTESTATIONOUTPUT.oneofs_by_name['mechanism'].fields.append(
  _PREPAREKEYATTESTATIONOUTPUT.fields_by_name['activate_credential'])
_PREPAREKEYATTESTATIONOUTPUT.fields_by_name['activate_credential'].containing_oneof = _PREPAREKEYATTESTATIONOUTPUT.oneofs_by_name['mechanism']
_RESULT.fields_by_name['output'].message_type = _PREPAREKEYATTESTATIONOUTPUT
DESCRIPTOR.message_types_by_name['PrepareKeyAttestationParams'] = _PREPAREKEYATTESTATIONPARAMS
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['PrepareKeyAttestationOutput'] = _PREPAREKEYATTESTATIONOUTPUT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrepareKeyAttestationParams = _reflection.GeneratedProtocolMessageType('PrepareKeyAttestationParams', (_message.Message,), {

  'ActivateCredential' : _reflection.GeneratedProtocolMessageType('ActivateCredential', (_message.Message,), {
    'DESCRIPTOR' : _PREPAREKEYATTESTATIONPARAMS_ACTIVATECREDENTIAL,
    '__module__' : 'prepare_key_attestation_pb2'
    # @@protoc_insertion_point(class_scope:prepare_key_attestation.PrepareKeyAttestationParams.ActivateCredential)
    })
  ,
  'DESCRIPTOR' : _PREPAREKEYATTESTATIONPARAMS,
  '__module__' : 'prepare_key_attestation_pb2'
  # @@protoc_insertion_point(class_scope:prepare_key_attestation.PrepareKeyAttestationParams)
  })
_sym_db.RegisterMessage(PrepareKeyAttestationParams)
_sym_db.RegisterMessage(PrepareKeyAttestationParams.ActivateCredential)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'prepare_key_attestation_pb2'
  # @@protoc_insertion_point(class_scope:prepare_key_attestation.Operation)
  })
_sym_db.RegisterMessage(Operation)

PrepareKeyAttestationOutput = _reflection.GeneratedProtocolMessageType('PrepareKeyAttestationOutput', (_message.Message,), {

  'ActivateCredential' : _reflection.GeneratedProtocolMessageType('ActivateCredential', (_message.Message,), {
    'DESCRIPTOR' : _PREPAREKEYATTESTATIONOUTPUT_ACTIVATECREDENTIAL,
    '__module__' : 'prepare_key_attestation_pb2'
    # @@protoc_insertion_point(class_scope:prepare_key_attestation.PrepareKeyAttestationOutput.ActivateCredential)
    })
  ,
  'DESCRIPTOR' : _PREPAREKEYATTESTATIONOUTPUT,
  '__module__' : 'prepare_key_attestation_pb2'
  # @@protoc_insertion_point(class_scope:prepare_key_attestation.PrepareKeyAttestationOutput)
  })
_sym_db.RegisterMessage(PrepareKeyAttestationOutput)
_sym_db.RegisterMessage(PrepareKeyAttestationOutput.ActivateCredential)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'prepare_key_attestation_pb2'
  # @@protoc_insertion_point(class_scope:prepare_key_attestation.Result)
  })
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
