# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: psa_raw_key_agreement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import psa_algorithm_pb2 as psa__algorithm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='psa_raw_key_agreement.proto',
  package='psa_raw_key_agreement',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bpsa_raw_key_agreement.proto\x12\x15psa_raw_key_agreement\x1a\x13psa_algorithm.proto\"o\n\tOperation\x12\x36\n\x03\x61lg\x18\x01 \x01(\x0e\x32).psa_algorithm.Algorithm.KeyAgreement.Raw\x12\x18\n\x10private_key_name\x18\x02 \x01(\t\x12\x10\n\x08peer_key\x18\x03 \x01(\x0c\"\x1f\n\x06Result\x12\x15\n\rshared_secret\x18\x01 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[psa__algorithm__pb2.DESCRIPTOR,])




_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='psa_raw_key_agreement.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alg', full_name='psa_raw_key_agreement.Operation.alg', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='private_key_name', full_name='psa_raw_key_agreement.Operation.private_key_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer_key', full_name='psa_raw_key_agreement.Operation.peer_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=186,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='psa_raw_key_agreement.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shared_secret', full_name='psa_raw_key_agreement.Result.shared_secret', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=219,
)

_OPERATION.fields_by_name['alg'].enum_type = psa__algorithm__pb2._ALGORITHM_KEYAGREEMENT_RAW
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), dict(
  DESCRIPTOR = _OPERATION,
  __module__ = 'psa_raw_key_agreement_pb2'
  # @@protoc_insertion_point(class_scope:psa_raw_key_agreement.Operation)
  ))
_sym_db.RegisterMessage(Operation)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'psa_raw_key_agreement_pb2'
  # @@protoc_insertion_point(class_scope:psa_raw_key_agreement.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
