# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: psa_hash_compute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import psa_algorithm_pb2 as psa__algorithm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='psa_hash_compute.proto',
  package='psa_hash_compute',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16psa_hash_compute.proto\x12\x10psa_hash_compute\x1a\x13psa_algorithm.proto\"F\n\tOperation\x12*\n\x03\x61lg\x18\x01 \x01(\x0e\x32\x1d.psa_algorithm.Algorithm.Hash\x12\r\n\x05input\x18\x02 \x01(\x0c\"\x16\n\x06Result\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[psa__algorithm__pb2.DESCRIPTOR,])




_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='psa_hash_compute.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alg', full_name='psa_hash_compute.Operation.alg', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='psa_hash_compute.Operation.input', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=135,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='psa_hash_compute.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='psa_hash_compute.Result.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=159,
)

_OPERATION.fields_by_name['alg'].enum_type = psa__algorithm__pb2._ALGORITHM_HASH
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), dict(
  DESCRIPTOR = _OPERATION,
  __module__ = 'psa_hash_compute_pb2'
  # @@protoc_insertion_point(class_scope:psa_hash_compute.Operation)
  ))
_sym_db.RegisterMessage(Operation)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'psa_hash_compute_pb2'
  # @@protoc_insertion_point(class_scope:psa_hash_compute.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
